deviceName=Pixel_4_API_30
platformVersion=11.0
platformName=Android
appPackage=com.example.healthsync
appActivity=com.example.healthsync.frontend.ui.activities.SplashActivity
appPath=app/HealthSync.apk
appiumServer=http://127.0.0.1:4723/wd/hub
